// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JobScheduler.Shared
{
    public partial class Schedule
    {
        public long Id { get; set; }
        public long? JobId { get; set; }
        public string Cron { get; set; }

        public virtual Jobs Job { get; set; }
    }
}